Repository Hwan007/TextRPGing, pull requests merged in 2023-08, with the labels that each got.

#8 feat/Enum 생성
  Define/Enum.cs
Labels: feature

#16 SceneManager 선언
  Manager/SceneManager.cs
Labels: feature

#31 feat/Inventory
  Model/Inventory.cs
Labels: feature

#34 Hwan
  Controller/EquipController.cs
  Manager/SceneManager.cs
  Model/Equipment.cs
  Scene/Town.cs
Labels: feature

#38 feat/Potion Weapon Armor 추가
  Model/Armor.cs
  Model/Potion.cs
  Model/Weapon.cs
Labels: feature

#43 캐릭터 클래스 ReStat() 메서드
  Model/Character.cs
  Scene/Recovery.cs
Labels: feature

#44 직업 프로퍼티, 캐릭터 생성자 추가
  Model/Character.cs
Labels: enhancement

#45 feat/InventoryController
  Controller/InventoryController.cs
  Manager/SceneManager.cs
  Model/Inventory.cs
Labels: feature

#48 Hwan
  Manager/SceneManager.cs
  Scene/Status.cs
  Scene/Town.cs
Labels: feature

#50 bug/버그픽스
  Manager/UIManager.cs
  Model/Inventory.cs
  TextRPGing.csproj
  Utils/IOSteream.cs
Labels: bug

#52 bugfix/GameManager
  Manager/GameManager.cs
  TextRPGing.csproj
  Utils/IOSteream.cs
Labels: bug

#56 씬매니저 버그 수정
  Manager/GameManager.cs
  Manager/SceneManager.cs
  Scene/Recovery.cs
  Scene/Status.cs
  Scene/Town.cs
Labels: bug

#59 인벤토리에 테스트용 포션 추가
  Model/Character.cs
  Scene/Recovery.cs
Labels: enhancement

#60 Hwan
  Manager/SceneManager.cs
  README.md
  Scene/Status.cs
  TextRPGing.drawio.png
Labels: bug

#61 리커버리 씬 선택지 개선
  Manager/SceneManager.cs
  Scene/Recovery.cs
  Scene/Status.cs
Labels: enhancement

#66 feat/SaveLoad2
  Data/PlayerData.json
  Data/ShopItem.json
  Model/Armor.cs
  Model/Character.cs
  Model/Item.cs
  Model/Potion.cs
  Model/Weapon.cs
  Scene/SaveLoad.cs
  Utils/IOSteream.cs
  Utils/IOStream.cs
Labels: feature

#68 인벤토리씬 이동 구현
  Manager/SceneManager.cs
  Scene/SInventory.cs
Labels: feature

#69 Fix/item
  Model/Item.cs
Labels: bug

#70 feat/Store item load
  Data/StoreItem.json
  Scene/Store.cs
  Utils/IOStream.cs
Labels: feature

#71 캐릭터 ReStat() 버그 수정
  Data/PlayerData.json
  Model/Armor.cs
  Model/Character.cs
  Model/Equipment.cs
  Model/Weapon.cs
  Scene/SInventory.cs
  Scene/Town.cs
Labels: bug

#73 feat/SaveLoad 초기 구현 완료
  .gitignore
  Data/PlayerData.json
  Manager/GameManager.cs
  Scene/SaveLoad.cs
  TextRPGing.csproj
Labels: feature

#75 bug/Store json 파일 불러오기 버그 수정 완료
  Scene/Store.cs
Labels: bug

#76 battle씬 작성
  Define/GameEnum.cs
  Define/Interface/IAction.cs
  Model/ActionResult.cs
  Model/Attack.cs
  Model/Character.cs
  Model/Monster.cs
  Model/Skill.cs
  Scene/Battle.cs
Labels: feature
