Repository Hwan007/TextRPGing, pull requests merged in 2023-09, with the labels that each got.

#77 Hwan
  Model/Equipment.cs
  Scene/Status.cs
Labels: bug

#84 인벤토리 완성
  Data/PlayerData.json
  Scene/SInventory.cs
Labels: feature

#86 마이너 버그 수정
  Scene/Recovery.cs
  Scene/SInventory.cs
  Scene/Status.cs
Labels: enhancement

#91 상점 아이템 구매 후 인벤토리 입장 시 버그 수정
  Model/Character.cs
  Model/Potion.cs
  Scene/SInventory.cs
  Scene/Store.cs
Labels: bug

#93 아이템 능력치 0으로 초기화되는 버그 수정
  Data/StoreItem.json
  Model/Armor.cs
  Model/Character.cs
  Model/Item.cs
  Model/Weapon.cs
  Scene/Store.cs
Labels: bug

#95 상점 버그 수정
  Data/StoreItem.json
  Scene/SInventory.cs
  Scene/Store.cs
Labels: bug

#96 Hwan
  Scene/Store.cs
Labels: bug

#98 refactor/SaveLoad Indented 포맷 추가
  Utils/IOStream.cs
Labels: feature

#100 Hwan
  Scene/Recovery.cs
  Scene/SInventory.cs
  Scene/Status.cs
  Scene/Town.cs
Labels: enhancement
